import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "surface-bright": "#39393b",
        "primary-fixed-dim": "#00dce6",
        "primary-container": "#00f3ff",
        "on-error": "#690005",
        "on-surface-variant": "#b9cacb",
        "secondary-fixed": "#ffdad8",
        "surface-container-high": "#2a2a2c",
        "on-primary-fixed-variant": "#004f53",
        "on-tertiary-fixed-variant": "#74009f",
        "on-background": "#e5e1e4",
        "surface-tint": "#00dce6",
        "inverse-on-surface": "#313032",
        "on-tertiary-container": "#9c00d2",
        "tertiary": "#fff6fc",
        "inverse-surface": "#e5e1e4",
        "on-secondary-fixed-variant": "#92001e",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#6ff6ff",
        "outline-variant": "#3a494b",
        "on-secondary": "#680012",
        "secondary-container": "#ff525c",
        "on-tertiary": "#520071",
        "on-secondary-container": "#5b000f",
        "tertiary-container": "#f5cfff",
        "surface-variant": "#353437",
        "on-secondary-fixed": "#410008",
        "secondary": "#ffb3b2",
        "background": "#131315",
        "surface": "#131315",
        "on-surface": "#e5e1e4",
        "secondary-fixed-dim": "#ffb3b2",
        "tertiary-fixed-dim": "#ecb2ff",
        "outline": "#849495",
        "surface-container-highest": "#353437",
        "on-primary-fixed": "#002022",
        "on-primary-container": "#006b71",
        "surface-container-lowest": "#0e0e10",
        "inverse-primary": "#00696f",
        "tertiary-fixed": "#f8d8ff",
        "surface-container-low": "#1c1b1d",
        "surface-container": "#201f21",
        "error": "#ffb4ab",
        "primary": "#e3fdff",
        "on-primary": "#00373a",
        "surface-dim": "#131315",
        "on-tertiary-fixed": "#320047",

        "obsidian": "#0a0a0c",
        "void": "#050505",
        "neon-cyan": "#00f3ff",
        "neon-pink": "#ff003c",
        "neon-purple": "#bd00ff",
        "text-muted": "#8a8a93"
      },
      fontFamily: {
        heading: ['var(--font-space-grotesk)'],
        body: ['var(--font-inter)'],
        mono: ['var(--font-jetbrains-mono)'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/container-queries')
  ],
}
export default config